version: '3'

volumes:
    logs:
        driver: local

services:
    php:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        working_dir: /var/www/html
        #expose:
        #    - "9000"
        ports:
            - 8055:443
            - 80:80
        volumes:
            - C:/projetos/areacentral:/var/www/html
            - logs:/var/www/logs
            - .docker/php/php.ini:/usr/local/etc/php/php.ini
            - .docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        links:
            - db
    db:
        image: mysql:5.7
        ports:
            - 3000:3306
        volumes:
            - /var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=public
        command: --sql_mode="NO_ENGINE_SUBSTITUTION"